### ISSUE TITLE
Card Hotbar Blocks Other Elements

### ISSUE THREAD

**Issue by haksanlulz** [Brownie79/fvtt-card-support#10]
The card hotbar blocks from clicking on other things, mainly the chat and the vtt. I've checked if it was due to interaction with other modules but even while this was the only module active it was still occurring. It hasn't blocked anything but interaction with the chat and vtt for me, but those are enough to be bothersome even if avoidable.

![image](https://user-images.githubusercontent.com/18426277/90964135-deeecb00-e48b-11ea-821d-41970976df19.png)
![image](https://user-images.githubusercontent.com/18426277/90964166-21180c80-e48c-11ea-80dc-0728a3bf24aa.png)

The area in pink is where is being affected, "card-hotbar".

**Comment by Norc** [comment]
Thanks to Zeel's excellent CSS PR, this should be resolved in the next release, except for an edge case if you move the player's hand of cards to the right (that part is still forthcoming).

**Comment by Norc** [comment]
Hey folks, just to follow-up, the last remnants of this issue should now be fixed as of 1.4.4. Please open a new issue if there are any lingering things I missed, thanks!
